/** Autogenerated by otemplate v. 0.2.0 */

#include <libintl.h>
#include <string.h>

#include <onion/onion.h>
#include <onion/dict.h>

typedef struct dict_res_t{
	onion_dict *dict;
	onion_response *res;
}dict_res;


void _13_otemplate_html_blocks_init(onion_dict *context);
void _13_otemplate_html(onion_dict *context, onion_response *res);
static void otemplate_f_0000(dict_res *dr, const char *key, const void *value, int flags);
static void otemplate_f_0001(onion_dict *context, onion_response *res);


onion_connection_status _13_otemplate_html_handler_page(onion_dict *context, onion_request *req, onion_response *res){

  _13_otemplate_html(context, res);

  return OCS_PROCESSED;
}


onion_handler *_13_otemplate_html_handler(onion_dict *context){
  return onion_handler_new((onion_handler_handler)_13_otemplate_html_handler_page, context, (onion_handler_private_data_free)onion_dict_free);
}


onion_connection_status _13_otemplate_html_template(onion_dict *context, onion_request *req, onion_response *res){

  if (context) onion_dict_add(context, "LANG", onion_request_get_language_code(req), OD_FREE_VALUE);

  _13_otemplate_html(context, res);

  if (context) onion_dict_free(context);

  return OCS_PROCESSED;
}

#line 1 "/home/tetsuya/work/ON.Lab/BGP_SDN_without_onion/BGP-SDN/opensource/onion/tests/01-internal/13-otemplate.html"
#line 1
void _13_otemplate_html_blocks_init(onion_dict *context){
#line 1
#line 1
}
#line 1
void _13_otemplate_html(onion_dict *context, onion_response *res){
#line 1
#line 1
  int has_context=(context!=NULL);
#line 1
  if (!has_context)
#line 1
    context=onion_dict_new();
#line 1
  
#line 1
  _13_otemplate_html_blocks_init(context);
#line 4
  onion_response_write(res, "\n<html>\n<head>\n  <title>", 24);
#line 4
  {
#line 4
    const char *tmp;
#line 4
    tmp=onion_dict_get(context, "title");
#line 4
    if (tmp)
#line 4
      onion_response_write0(res, tmp);
#line 4
  }
#line 7
  onion_response_write(res, "</title>\n</head>\n<body>\n<h1>", 28);
#line 7
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "List"));
#line 9
  onion_response_write(res, "</h1>\n<ul>\n", 11);
#line 9
  {
#line 9
    onion_dict *loopdict=onion_dict_get_dict(context, "list");
#line 9
    onion_dict *tmpcontext=onion_dict_hard_dup(context);
#line 9
    if (loopdict){
#line 9
      dict_res dr={ .dict = tmpcontext, .res=res };
#line 9
      onion_dict_preorder(loopdict, 
#line 11
otemplate_f_0000, &dr);
#line 11
    }
#line 11
    onion_dict_free(tmpcontext);
#line 11
  }
#line 13
  onion_response_write(res, "\n</ul>\n<h2>", 11);
#line 15
  onion_response_write(res, "{hello}</h2>\n\n", 14);
#line 15
  {
#line 15
    const char *tmp;
#line 15
    tmp=onion_dict_get(context, "title");
#line 15
    if (tmp)
#line 15
      onion_response_write0(res, tmp);
#line 15
  }
#line 15
  onion_response_write(res, " ", 1);
#line 15
  {
#line 15
    const char *tmp;
#line 15
    tmp=onion_dict_get(context, "title");
#line 15
    if (tmp)
#line 15
      onion_response_write0(res, tmp);
#line 15
  }
#line 18
  onion_response_write(res, "\n</body>\n\n", 10);
#line 18
  if (!has_context)
#line 18
    onion_dict_free(context);
#line 1
}
#line 1
static void otemplate_f_0000(dict_res *dr, const char *key, const void *value, int flags){
#line 1
#line 9
  onion_dict_add(dr->dict, "i", value, OD_DUP_VALUE|OD_REPLACE|(flags&OD_TYPE_MASK));
#line 11
  otemplate_f_0001(dr->dict, dr->res);
#line 1
}
#line 1
static void otemplate_f_0001(onion_dict *context, onion_response *res){
#line 1
#line 10
  onion_response_write(res, "\n<li>", 5);
#line 10
  {
#line 10
    const char *tmp;
#line 10
    tmp=onion_dict_get(context, "i");
#line 10
    if (tmp)
#line 10
      onion_response_write0(res, tmp);
#line 10
  }
#line 11
  onion_response_write(res, "</li>\n", 6);
#line 1
}
