/** Autogenerated by otemplate v. 0.2.0 */

#include <libintl.h>
#include <string.h>

#include <onion/onion.h>
#include <onion/dict.h>

typedef struct dict_res_t{
	onion_dict *dict;
	onion_response *res;
}dict_res;


void fileserver_html_blocks_init(onion_dict *context);
void fileserver_html(onion_dict *context, onion_response *res);
static void otemplate_f_0000(onion_dict *context, onion_response *res);
static void otemplate_f_0001(dict_res *dr, const char *key, const void *value, int flags);
static void otemplate_f_0002(onion_dict *context, onion_response *res);
static void otemplate_f_0003(onion_dict *context, onion_response *res);
static void otemplate_f_0004(onion_dict *context, onion_response *res);


onion_connection_status fileserver_html_handler_page(onion_dict *context, onion_request *req, onion_response *res){

  fileserver_html(context, res);

  return OCS_PROCESSED;
}


onion_handler *fileserver_html_handler(onion_dict *context){
  return onion_handler_new((onion_handler_handler)fileserver_html_handler_page, context, (onion_handler_private_data_free)onion_dict_free);
}


onion_connection_status fileserver_html_template(onion_dict *context, onion_request *req, onion_response *res){

  if (context) onion_dict_add(context, "LANG", onion_request_get_language_code(req), OD_FREE_VALUE);

  fileserver_html(context, res);

  if (context) onion_dict_free(context);

  return OCS_PROCESSED;
}

#line 1 "/home/tetsuya/work/ON.Lab/BGP_SDN_without_onion/BGP-SDN/opensource/onion/examples/ofileserver/fileserver.html"
#line 1
void fileserver_html_blocks_init(onion_dict *context){
#line 1
#line 1
}
#line 1
void fileserver_html(onion_dict *context, onion_response *res){
#line 1
#line 1
  int has_context=(context!=NULL);
#line 1
  if (!has_context)
#line 1
    context=onion_dict_new();
#line 1
  
#line 1
  fileserver_html_blocks_init(context);
#line 5
  onion_response_write(res, "\n<html>\n<head>\n <meta content=\"text/html; charset=UTF-8\" http-equiv=\"content-type\"/> \n <title>", 94);
#line 5
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Current directory: "));
#line 5
  onion_response_write(res, " ", 1);
#line 5
  {
#line 5
    const char *tmp;
#line 5
    tmp=onion_dict_get(context, "dirname");
#line 5
    if (tmp)
#line 5
      onion_response_write0(res, tmp);
#line 5
  }
#line 7
  onion_response_write(res, "</title>\n<style>\nbody", 21);
#line 8
  onion_response_write(res, "{ background: #fefefe; font-family: sans-serif; margin-left: 5%; margin-right: 5%; }\ntable", 90);
#line 9
  onion_response_write(res, "{ background: white; width: 100%; border: 1px solid #aaa; border-radius: 5px; -moz-border-radius: 5px; }\nth", 107);
#line 9
  onion_response_write(res, "{\tbackground: #eee; } tbody tr:hover td", 39);
#line 9
  onion_response_write(res, "{ background: yellow; } tr.dir td", 33);
#line 10
  onion_response_write(res, "{ background: #D4F0FF; }\ntable a", 32);
#line 10
  onion_response_write(res, "{ display: block; } th", 22);
#line 10
  onion_response_write(res, "{ cursor: pointer} h1,h2", 24);
#line 11
  onion_response_write(res, "{ color: black; text-align: center; }\na", 39);
#line 12
  onion_response_write(res, "{ color: red; text-decoration: none; }\n#copyright", 49);
#line 13
  onion_response_write(res, "{ text-align: center; font-size: 0.7em; }\n#lang", 47);
#line 20
  onion_response_write(res, "{ size: 0.6em; color: #aaa; }\n</style>\n\n</style>\n</head>\n<body>\n\n<h1>", 69);
#line 20
  {
#line 20
    const char *tmp;
#line 20
    tmp=onion_dict_get(context, "dirname");
#line 20
    if (tmp)
#line 20
      onion_response_write0(res, tmp);
#line 20
  }
#line 22
  onion_response_write(res, "</h1>\n\n", 7);
#line 22
  {
#line 22
    const char *tmp;
#line 22
    tmp=onion_dict_get(context, "go_up");
#line 22
    if (tmp && strcmp(tmp, "false")!=0)
#line 22
      otemplate_f_0000(context, res);
#line 22
  }
#line 26
  onion_response_write(res, "\n\n<table>\n<thead>\n <tr><th>", 27);
#line 26
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Filename"));
#line 26
  onion_response_write(res, "</th><th>", 9);
#line 26
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Size"));
#line 26
  onion_response_write(res, "</th><th>", 9);
#line 26
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Owner"));
#line 29
  onion_response_write(res, "</th></tr>\n</thead>\n<tbody>\n", 28);
#line 29
  {
#line 29
    onion_dict *loopdict=onion_dict_get_dict(context, "files");
#line 29
    onion_dict *tmpcontext=onion_dict_hard_dup(context);
#line 29
    if (loopdict){
#line 29
      dict_res dr={ .dict = tmpcontext, .res=res };
#line 29
      onion_dict_preorder(loopdict, 
#line 35
otemplate_f_0001, &dr);
#line 35
    }
#line 35
    onion_dict_free(tmpcontext);
#line 35
  }
#line 39
  onion_response_write(res, "\n</tbody>\n</table>\n\n<div id=\"copyright\">(C) 2011 <a href=\"http://www.coralbits.com\">Coralbits S.L</a> ", 102);
#line 39
  {
#line 39
    const char *tmp;
#line 39
    tmp=onion_dict_get(context, "LANG");
#line 39
    if (tmp && strcmp(tmp, "false")!=0)
#line 39
      otemplate_f_0004(context, res);
#line 39
  }
#line 43
  onion_response_write(res, "</div>\n\n</body>\n</html>\n", 24);
#line 43
  if (!has_context)
#line 43
    onion_dict_free(context);
#line 1
}
#line 1
static void otemplate_f_0000(onion_dict *context, onion_response *res){
#line 1
#line 22
  onion_response_write(res, "<a href=\"..\">", 13);
#line 22
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Go up"));
#line 22
  onion_response_write(res, "</a>", 4);
#line 1
}
#line 1
static void otemplate_f_0001(dict_res *dr, const char *key, const void *value, int flags){
#line 1
#line 29
  onion_dict_add(dr->dict, "file", value, OD_DUP_VALUE|OD_REPLACE|(flags&OD_TYPE_MASK));
#line 35
  otemplate_f_0002(dr->dict, dr->res);
#line 1
}
#line 1
static void otemplate_f_0002(onion_dict *context, onion_response *res){
#line 1
#line 31
  onion_response_write(res, "\n <tr>\n  <td><a href=\"", 22);
#line 31
  {
#line 31
    const char *tmp;
#line 31
    tmp=onion_dict_rget(context
#line 31
, "file"
#line 31
, "name"
#line 31
, NULL);
#line 31
    if (tmp)
#line 31
      onion_response_write0(res, tmp);
#line 31
  }
#line 31
  {
#line 31
    const char *op1, *op2;
#line 31
    op1=onion_dict_rget(context
#line 31
, "file"
#line 31
, "type"
#line 31
, NULL);
#line 31
    op2="dir";
#line 31
    if (op1==op2 || (op1 && op2 && strcmp(op1, op2)==0))
#line 31
      otemplate_f_0003(context, res);
#line 31
  }
#line 31
  onion_response_write(res, "\">", 2);
#line 31
  {
#line 31
    const char *tmp;
#line 31
    tmp=onion_dict_rget(context
#line 31
, "file"
#line 31
, "name"
#line 31
, NULL);
#line 31
    if (tmp)
#line 31
      onion_response_write0(res, tmp);
#line 31
  }
#line 32
  onion_response_write(res, "</a></td>\n  <td>", 16);
#line 32
  {
#line 32
    const char *tmp;
#line 32
    tmp=onion_dict_rget(context
#line 32
, "file"
#line 32
, "size"
#line 32
, NULL);
#line 32
    if (tmp)
#line 32
      onion_response_write0(res, tmp);
#line 32
  }
#line 33
  onion_response_write(res, "</td>\n  <td>", 12);
#line 33
  {
#line 33
    const char *tmp;
#line 33
    tmp=onion_dict_rget(context
#line 33
, "file"
#line 33
, "owner"
#line 33
, NULL);
#line 33
    if (tmp)
#line 33
      onion_response_write0(res, tmp);
#line 33
  }
#line 35
  onion_response_write(res, "</td>\n </tr>\n", 13);
#line 1
}
#line 1
static void otemplate_f_0003(onion_dict *context, onion_response *res){
#line 1
#line 31
  onion_response_write(res, "/", 1);
#line 1
}
#line 1
static void otemplate_f_0004(onion_dict *context, onion_response *res){
#line 1
#line 39
  onion_response_write(res, "<span id=\"lang\">", 16);
#line 39
  {
#line 39
    const char *tmp;
#line 39
    tmp=onion_dict_get(context, "LANG");
#line 39
    if (tmp)
#line 39
      onion_response_write0(res, tmp);
#line 39
  }
#line 1
}
