/** Autogenerated by otemplate v. 0.2.0 */

#include <libintl.h>
#include <string.h>

#include <onion/onion.h>
#include <onion/dict.h>

typedef struct dict_res_t{
	onion_dict *dict;
	onion_response *res;
}dict_res;


void mandel_html_blocks_init(onion_dict *context);
void mandel_html(onion_dict *context, onion_response *res);


onion_connection_status mandel_html_handler_page(onion_dict *context, onion_request *req, onion_response *res){

  mandel_html(context, res);

  return OCS_PROCESSED;
}


onion_handler *mandel_html_handler(onion_dict *context){
  return onion_handler_new((onion_handler_handler)mandel_html_handler_page, context, (onion_handler_private_data_free)onion_dict_free);
}


onion_connection_status mandel_html_template(onion_dict *context, onion_request *req, onion_response *res){

  if (context) onion_dict_add(context, "LANG", onion_request_get_language_code(req), OD_FREE_VALUE);

  mandel_html(context, res);

  if (context) onion_dict_free(context);

  return OCS_PROCESSED;
}

#line 1 "/home/tetsuya/work/ON.Lab/BGP_SDN_without_onion/BGP-SDN/opensource/onion/examples/mandelbrot/mandel.html"
#line 1
void mandel_html_blocks_init(onion_dict *context){
#line 1
#line 1
}
#line 1
void mandel_html(onion_dict *context, onion_response *res){
#line 1
#line 1
  int has_context=(context!=NULL);
#line 1
  if (!has_context)
#line 1
    context=onion_dict_new();
#line 1
  
#line 1
  mandel_html_blocks_init(context);
#line 6
  onion_response_write(res, "<html>\n<header>\n<title>Mandelbrot explorer</title>\n<style>\nbody", 63);
#line 9
  onion_response_write(res, "{\n\tfont-family: sans-serif;\n}\na", 31);
#line 43
  onion_response_write(res, "{\n\tcolor: #FF2740;\n}\n</style>\n</header>\n<body>\n\n<h1>Use mouse wheel to zoom in and out.</h1>\n<img src=\"mandel.png?width=512&height=512&zoom=1.0&X=-2.0&Y=-2.0\" id=\"mandel\" \n\t\t onmousedown=\"mandelMoveDown(event)\" onmouseup=\"mandelMoveUp(event)\"  onmousewheel=\"mandelZoom(event)\" style=\"float: left; margin-right: 2em;\">\nAll data is processed at the server and sent back to the client.\n<ul>\n <li> Zoom <b id=\"zoom\">1.0</b></li>\n <li> Position (<b id=\"X\">-2.0</b>, <b id=\"Y\">2.0</b>)</li>\n</ul>\n\n\n<br style=\"clear: left;\">\nTested on Google Chrome.\n<br>\n(C)2011 <a href=\"http://www.coralbits.com\">Coralbits S.L.</a> Under AGPL license.\n\n<script>\nX=-2.5\nY=-2.0\nwidth=512.0\nheight=512.0\nzoom=1.0\nW=4.0\nH=4.0\n\nmouseDownX=0\nmouseDownY=0\n\nmandelMoveDown = function(ev)", 758);
#line 53
  onion_response_write(res, "{\n\tsX=ev.offsetX || ev.clientX\n\tsY=ev.offsetY || ev.clientY\n\n\tmouseDownX=X+(sX/width)*W\n\tmouseDownY=Y+(sY/height)*H\n\n\tev.preventDefault()\n}\n\nmandelMoveUp = function(ev)", 168);
#line 73
  onion_response_write(res, "{\n\tsX=ev.offsetX || ev.clientX\n\tsY=ev.offsetY || ev.clientY\n\n\trealX=X+(sX/width)*W\n\trealY=Y+(sY/height)*H\n\n\tX+=mouseDownX-realX\n\tY+=mouseDownY-realY\n\n\tmandelRefresh();\n\n\tev.preventDefault()\n}\n\n/**\n * Zooms on the current point. \n *\n * It forces the mouse where it is in, to stay there.\n */\nmandelZoom = function(ev)", 315);
#line 96
  onion_response_write(res, "{\n\tsX=ev.offsetX || ev.clientX\n\tsY=ev.offsetY || ev.clientY\n\t\n\trealX=X+(sX/width)*W\n\trealY=Y+(sY/height)*H\n\n\tif ((ev.wheelDelta || -ev.detail)>0)\n\t\tzoom=1.1;\n\telse\n\t\tzoom=1/1.1;\n\n\tW=W/zoom\n\tH=H/zoom\n\n\tX=realX-(sX/width)*W\n\tY=realY-(sY/height)*H\n\n\tmandelRefresh()\n\tev.preventDefault();\n}\n\nt=0\nmandelRefresh = function()", 318);
#line 98
  onion_response_write(res, "{\n\tclearTimeout(t)\n\tt=setTimeout(function()", 43);
#line 112
  onion_response_write(res, "{\n\t\tdocument.getElementById(\"mandel\").src=\"mandel.png?width=\"+width+\"&height=\"+height+\"&W=\"+W+\"&H=\"+H+\"&X=\"+X+\"&Y=\"+Y;\n\t\tdocument.getElementById(\"zoom\").innerText=zoom\n\t\tdocument.getElementById(\"X\").innerText=X\n\t\tdocument.getElementById(\"Y\").innerText=Y\n\t}, 50)\n}\n\nmandelRefresh()\nif (window.addEventListener)\n        /** DOMMouseScroll is for mozilla. */\n        document.getElementById(\"mandel\").addEventListener('DOMMouseScroll', mandelZoom, false);\n</script>\n\n</body>\n", 472);
#line 112
  if (!has_context)
#line 112
    onion_dict_free(context);
#line 1
}
