/** Autogenerated by otemplate v. 0.2.0 */

#include <libintl.h>
#include <string.h>

#include <onion/onion.h>
#include <onion/dict.h>

typedef struct dict_res_t{
	onion_dict *dict;
	onion_response *res;
}dict_res;


void base_html_blocks_init(onion_dict *context);
void base_html(onion_dict *context, onion_response *res);
void base_html__block_title(onion_dict *context, onion_response *res);
void base_html__block_body(onion_dict *context, onion_response *res);


onion_connection_status base_html_handler_page(onion_dict *context, onion_request *req, onion_response *res){

  base_html(context, res);

  return OCS_PROCESSED;
}


onion_handler *base_html_handler(onion_dict *context){
  return onion_handler_new((onion_handler_handler)base_html_handler_page, context, (onion_handler_private_data_free)onion_dict_free);
}


onion_connection_status base_html_template(onion_dict *context, onion_request *req, onion_response *res){

  if (context) onion_dict_add(context, "LANG", onion_request_get_language_code(req), OD_FREE_VALUE);

  base_html(context, res);

  if (context) onion_dict_free(context);

  return OCS_PROCESSED;
}

#line 1 "/home/tetsuya/work/ON.Lab/BGP_SDN_without_onion/BGP-SDN/opensource/onion/tests/07-otemplate/base.html"
#line 1
void base_html_blocks_init(onion_dict *context){
#line 1
  if (!onion_dict_get(context, "__block_title__"))
    onion_dict_add(context, "__block_title__", base_html__block_title, 0);
  if (!onion_dict_get(context, "__block_body__"))
    onion_dict_add(context, "__block_body__", base_html__block_body, 0);
#line 1
}
#line 1
void base_html(onion_dict *context, onion_response *res){
#line 1
#line 1
  int has_context=(context!=NULL);
#line 1
  if (!has_context)
#line 1
    context=onion_dict_new();
#line 1
  
#line 1
  base_html_blocks_init(context);
#line 4
  onion_response_write(res, "<html>\n <head>\n\t<meta content=\"text/html; charset=UTF-8\" http-equiv=\"content-type\"> </meta>\n  <title>", 101);
#line 4
  {
#line 4
    void (*f)(onion_dict *context, onion_response *res);
#line 4
    f=(void*)onion_dict_get(context, "__block_title__");
#line 4
    if (f)
#line 4
      f(context, res);
#line 4
  }
#line 7
  onion_response_write(res, "</title>\n </head>\n<body>\n", 25);
#line 7
  {
#line 7
    void (*f)(onion_dict *context, onion_response *res);
#line 7
    f=(void*)onion_dict_get(context, "__block_body__");
#line 7
    if (f)
#line 7
      f(context, res);
#line 7
  }
#line 14
  onion_response_write(res, "\n<p>\nThis should appear, as is outside block.\n</body>\n</html>\n", 62);
#line 14
  if (!has_context)
#line 14
    onion_dict_free(context);
#line 1
}
#line 1
void base_html__block_title(onion_dict *context, onion_response *res){
#line 1
#line 4
  onion_response_write(res, "No title", 8);
#line 1
}
#line 1
void base_html__block_body(onion_dict *context, onion_response *res){
#line 1
#line 9
  onion_response_write(res, "\nNo body. If you see this, <span style=\"color: red;\">ERROR</span>.\n", 67);
#line 1
}
