/** Autogenerated by otemplate v. 0.2.0 */

#include <libintl.h>
#include <string.h>

#include <onion/onion.h>
#include <onion/dict.h>

typedef struct dict_res_t{
	onion_dict *dict;
	onion_response *res;
}dict_res;


void external_html_blocks_init(onion_dict *context);
void external_html(onion_dict *context, onion_response *res);


onion_connection_status external_html_handler_page(onion_dict *context, onion_request *req, onion_response *res){

  external_html(context, res);

  return OCS_PROCESSED;
}


onion_handler *external_html_handler(onion_dict *context){
  return onion_handler_new((onion_handler_handler)external_html_handler_page, context, (onion_handler_private_data_free)onion_dict_free);
}


onion_connection_status external_html_template(onion_dict *context, onion_request *req, onion_response *res){

  if (context) onion_dict_add(context, "LANG", onion_request_get_language_code(req), OD_FREE_VALUE);

  external_html(context, res);

  if (context) onion_dict_free(context);

  return OCS_PROCESSED;
}

#line 1 "/home/tetsuya/work/ON.Lab/BGP_SDN_without_onion/BGP-SDN/opensource/onion/tests/07-otemplate/external.html"
#line 1
void external_html_blocks_init(onion_dict *context){
#line 1
#line 1
}
#line 1
void external_html(onion_dict *context, onion_response *res){
#line 1
#line 1
  int has_context=(context!=NULL);
#line 1
  if (!has_context)
#line 1
    context=onion_dict_new();
#line 1
  
#line 1
  external_html_blocks_init(context);
#line 2
  onion_response_write(res, "This code is in an external html.\n", 34);
#line 2
  if (!has_context)
#line 2
    onion_dict_free(context);
#line 1
}
