/** Autogenerated by otemplate v. 0.2.0 */

#include <libintl.h>
#include <string.h>

#include <onion/onion.h>
#include <onion/dict.h>

typedef struct dict_res_t{
	onion_dict *dict;
	onion_response *res;
}dict_res;


void extended_html_blocks_init(onion_dict *context);
void extended_html(onion_dict *context, onion_response *res);
void base_html(onion_dict *context, onion_response *res);
void extended_html__block_title(onion_dict *context, onion_response *res);
void extended_html__block_body(onion_dict *context, onion_response *res);
void extended_html__block_body_in(onion_dict *context, onion_response *res);


onion_connection_status extended_html_handler_page(onion_dict *context, onion_request *req, onion_response *res){

  extended_html(context, res);

  return OCS_PROCESSED;
}


onion_handler *extended_html_handler(onion_dict *context){
  return onion_handler_new((onion_handler_handler)extended_html_handler_page, context, (onion_handler_private_data_free)onion_dict_free);
}


onion_connection_status extended_html_template(onion_dict *context, onion_request *req, onion_response *res){

  if (context) onion_dict_add(context, "LANG", onion_request_get_language_code(req), OD_FREE_VALUE);

  extended_html(context, res);

  if (context) onion_dict_free(context);

  return OCS_PROCESSED;
}

#line 1 "/home/tetsuya/work/ON.Lab/BGP_SDN_without_onion/BGP-SDN/opensource/onion/tests/07-otemplate/extended.html"
#line 1
void extended_html_blocks_init(onion_dict *context){
#line 1
  if (!onion_dict_get(context, "__block_title__"))
    onion_dict_add(context, "__block_title__", extended_html__block_title, 0);
  if (!onion_dict_get(context, "__block_body__"))
    onion_dict_add(context, "__block_body__", extended_html__block_body, 0);
  if (!onion_dict_get(context, "__block_body_in__"))
    onion_dict_add(context, "__block_body_in__", extended_html__block_body_in, 0);
#line 1
}
#line 1
void extended_html(onion_dict *context, onion_response *res){
#line 1
#line 1
  int has_context=(context!=NULL);
#line 1
  if (!has_context)
#line 1
    context=onion_dict_new();
#line 1
  
#line 1
  extended_html_blocks_init(context);
#line 1
  base_html(context, res);
#line 20
  if (!has_context)
#line 20
    onion_dict_free(context);
#line 1
}
#line 1
void extended_html__block_title(onion_dict *context, onion_response *res){
#line 1
#line 3
  onion_response_write(res, "Extended", 8);
#line 1
}
#line 1
void extended_html__block_body(onion_dict *context, onion_response *res){
#line 1
#line 8
  onion_response_write(res, "\n<h1>This is an extended template</h1>\n\n", 40);
#line 8
  {
#line 8
    void (*f)(onion_dict *context, onion_response *res);
#line 8
    f=(void*)onion_dict_get(context, "__block_body_in__");
#line 8
    if (f)
#line 8
      f(context, res);
#line 8
  }
#line 14
  onion_response_write(res, "\n\nIf you see this, <span style=\"color: green;\">OK</span>.\n<br>\nRandom (only at test2): ", 87);
#line 14
  {
#line 14
    const char *tmp;
#line 14
    tmp=onion_dict_get(context, "random");
#line 14
    if (tmp)
#line 14
      onion_response_write0(res, tmp);
#line 14
  }
#line 19
  onion_response_write(res, "\n<br>\n\nUnicode Chars: \342\202\254 \302\241 \303\241 \303\251 \303\255 \303\272 \303\263. \346\261\211\350\257\255/\346\274\242\350\252\236.\n\n", 61);
#line 1
}
#line 1
void extended_html__block_body_in(onion_dict *context, onion_response *res){
#line 1
#line 10
  onion_response_write(res, "\nMore text.\n", 12);
#line 1
}
