/** Autogenerated by otemplate v. 0.2.0 */

#include <libintl.h>
#include <string.h>

#include <onion/onion.h>
#include <onion/dict.h>

typedef struct dict_res_t{
	onion_dict *dict;
	onion_response *res;
}dict_res;


void test_html_blocks_init(onion_dict *context);
void test_html(onion_dict *context, onion_response *res);
static void otemplate_f_0000(onion_dict *context, onion_response *res);
static void otemplate_f_0001(onion_dict *context, onion_response *res);
static void otemplate_f_0002(onion_dict *context, onion_response *res);
static void otemplate_f_0003(onion_dict *context, onion_response *res);
static void otemplate_f_0004(onion_dict *context, onion_response *res);
static void otemplate_f_0005(onion_dict *context, onion_response *res);
static void otemplate_f_0006(onion_dict *context, onion_response *res);
static void otemplate_f_0007(onion_dict *context, onion_response *res);
static void otemplate_f_0008(dict_res *dr, const char *key, const void *value, int flags);
static void otemplate_f_0009(onion_dict *context, onion_response *res);
void external_html(onion_dict *context, onion_response *res);


onion_connection_status test_html_handler_page(onion_dict *context, onion_request *req, onion_response *res){

  test_html(context, res);

  return OCS_PROCESSED;
}


onion_handler *test_html_handler(onion_dict *context){
  return onion_handler_new((onion_handler_handler)test_html_handler_page, context, (onion_handler_private_data_free)onion_dict_free);
}


onion_connection_status test_html_template(onion_dict *context, onion_request *req, onion_response *res){

  if (context) onion_dict_add(context, "LANG", onion_request_get_language_code(req), OD_FREE_VALUE);

  test_html(context, res);

  if (context) onion_dict_free(context);

  return OCS_PROCESSED;
}

#line 1 "/home/tetsuya/work/ON.Lab/BGP_SDN_without_onion/BGP-SDN/opensource/onion/tests/07-otemplate/test.html"
#line 1
void test_html_blocks_init(onion_dict *context){
#line 1
#line 1
}
#line 1
void test_html(onion_dict *context, onion_response *res){
#line 1
#line 1
  int has_context=(context!=NULL);
#line 1
  if (!has_context)
#line 1
    context=onion_dict_new();
#line 1
  
#line 1
  test_html_blocks_init(context);
#line 4
  onion_response_write(res, "\n<html>\n<head>\n <title>", 23);
#line 4
  {
#line 4
    const char *tmp;
#line 4
    tmp=onion_dict_get(context, "title");
#line 4
    if (tmp)
#line 4
      onion_response_write0(res, tmp);
#line 4
  }
#line 8
  onion_response_write(res, "</title>\n</head>\n<body>\n\n<h1>", 29);
#line 8
  {
#line 8
    const char *tmp;
#line 8
    tmp=onion_dict_get(context, "title");
#line 8
    if (tmp)
#line 8
      onion_response_write0(res, tmp);
#line 8
  }
#line 10
  onion_response_write(res, "</h1>\n\n<h2>", 11);
#line 10
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Test vars."));
#line 13
  onion_response_write(res, "</h2>\n<p>\n<ul>\n<li>", 19);
#line 13
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Random value"));
#line 13
  onion_response_write(res, " ", 1);
#line 13
  {
#line 13
    const char *tmp;
#line 13
    tmp=onion_dict_get(context, "random");
#line 13
    if (tmp)
#line 13
      onion_response_write0(res, tmp);
#line 13
  }
#line 14
  onion_response_write(res, ".\n<li>", 6);
#line 14
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "sub.0"));
#line 14
  onion_response_write(res, " ", 1);
#line 14
  {
#line 14
    const char *tmp;
#line 14
    tmp=onion_dict_rget(context
#line 14
, "subd"
#line 14
, "0"
#line 14
, NULL);
#line 14
    if (tmp)
#line 14
      onion_response_write0(res, tmp);
#line 14
  }
#line 15
  onion_response_write(res, ".\n<li>", 6);
#line 15
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Not found"));
#line 15
  onion_response_write(res, " ", 1);
#line 15
  {
#line 15
    const char *tmp;
#line 15
    tmp=onion_dict_get(context, "does-not-exists");
#line 15
    if (tmp)
#line 15
      onion_response_write0(res, tmp);
#line 15
  }
#line 16
  onion_response_write(res, ".\n<li>", 6);
#line 16
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Not found trans"));
#line 16
  onion_response_write(res, " ", 1);
#line 16
  {
#line 16
    const char *tmp;
#line 16
    tmp=onion_dict_rget(context
#line 16
, "subd"
#line 16
, "0"
#line 16
, "1"
#line 16
, NULL);
#line 16
    if (tmp)
#line 16
      onion_response_write0(res, tmp);
#line 16
  }
#line 20
  onion_response_write(res, ".\n</ul>\n\n\n<h2>", 14);
#line 20
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Test if"));
#line 23
  onion_response_write(res, "</h2>\n\n<p>\n", 11);
#line 23
  {
#line 23
    const char *tmp;
#line 23
    tmp=onion_dict_get(context, "random");
#line 23
    if (tmp && strcmp(tmp, "false")!=0)
#line 25
      otemplate_f_0000(context, res);
#line 25
    else
#line 27
      otemplate_f_0001(context, res);
#line 27
  }
#line 30
  onion_response_write(res, "\n</p>\n<p>\n", 10);
#line 30
  {
#line 30
    const char *tmp;
#line 30
    tmp=onion_dict_get(context, "subd");
#line 30
    if (tmp && strcmp(tmp, "false")!=0)
#line 32
      otemplate_f_0002(context, res);
#line 32
    else
#line 34
      otemplate_f_0003(context, res);
#line 34
  }
#line 38
  onion_response_write(res, "\n access elements on if.</p>\n\n<p>\n", 34);
#line 38
  {
#line 38
    const char *tmp;
#line 38
    tmp=onion_dict_rget(context
#line 38
, "subd"
#line 38
, "0"
#line 38
, NULL);
#line 38
    if (tmp && strcmp(tmp, "false")!=0)
#line 40
      otemplate_f_0004(context, res);
#line 40
    else
#line 42
      otemplate_f_0005(context, res);
#line 42
  }
#line 46
  onion_response_write(res, "\n access subelements on if. </p>\n\n<p>\n", 38);
#line 46
  {
#line 46
    const char *tmp;
#line 46
    tmp=onion_dict_get(context, "empty");
#line 46
    if (tmp && strcmp(tmp, "false")!=0)
#line 48
      otemplate_f_0006(context, res);
#line 48
    else
#line 50
      otemplate_f_0007(context, res);
#line 50
  }
#line 57
  onion_response_write(res, "\nEmpty element do not enter true if\n</p>\n\n\n\n\n<h2>", 49);
#line 57
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Test for"));
#line 59
  onion_response_write(res, "</h2>\n<ul>\n", 11);
#line 59
  {
#line 59
    onion_dict *loopdict=onion_dict_get_dict(context, "subd");
#line 59
    onion_dict *tmpcontext=onion_dict_hard_dup(context);
#line 59
    if (loopdict){
#line 59
      dict_res dr={ .dict = tmpcontext, .res=res };
#line 59
      onion_dict_preorder(loopdict, 
#line 61
otemplate_f_0008, &dr);
#line 61
    }
#line 61
    onion_dict_free(tmpcontext);
#line 61
  }
#line 64
  onion_response_write(res, "\n</ul>\n\n<h2>", 12);
#line 64
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Test include"));
#line 65
  onion_response_write(res, "</h2>\n", 6);
#line 65
  external_html(context, res);
#line 67
  onion_response_write(res, "\n\n<h2>", 6);
#line 67
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "Test some C code"));
#line 71
  onion_response_write(res, "</h2>\n\n<pre>\nint argc(int argv, char **argv)", 44);
#line 77
  onion_response_write(res, "{\n\tprintf(\"Hello world!\\n\");\n}\n</pre>\n\n</body>\n</html>\n", 55);
#line 77
  if (!has_context)
#line 77
    onion_dict_free(context);
#line 1
}
#line 1
static void otemplate_f_0000(onion_dict *context, onion_response *res){
#line 1
#line 24
  onion_response_write(res, "\n<span style=\"color: green;\">OK</span> ", 39);
#line 24
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "random is present"));
#line 25
  onion_response_write(res, "\n", 1);
#line 1
}
#line 1
static void otemplate_f_0001(onion_dict *context, onion_response *res){
#line 1
#line 26
  onion_response_write(res, "\n<span style=\"color: red;\">ERROR</span> ", 40);
#line 26
  onion_response_write0(res, dgettext(onion_dict_get(context, "LANG"), "random is not present"));
#line 27
  onion_response_write(res, "\n", 1);
#line 1
}
#line 1
static void otemplate_f_0002(onion_dict *context, onion_response *res){
#line 1
#line 32
  onion_response_write(res, "\n<span style=\"color: green;\">OK</span>\n", 39);
#line 1
}
#line 1
static void otemplate_f_0003(onion_dict *context, onion_response *res){
#line 1
#line 34
  onion_response_write(res, "\n<span style=\"color: red;\">ERROR</span>\n", 40);
#line 1
}
#line 1
static void otemplate_f_0004(onion_dict *context, onion_response *res){
#line 1
#line 40
  onion_response_write(res, "\n<span style=\"color: green;\">OK</span>\n", 39);
#line 1
}
#line 1
static void otemplate_f_0005(onion_dict *context, onion_response *res){
#line 1
#line 42
  onion_response_write(res, "\n<span style=\"color: red;\">ERROR</span>\n", 40);
#line 1
}
#line 1
static void otemplate_f_0006(onion_dict *context, onion_response *res){
#line 1
#line 48
  onion_response_write(res, "\n<span style=\"color: red;\">ERROR</span>\n", 40);
#line 1
}
#line 1
static void otemplate_f_0007(onion_dict *context, onion_response *res){
#line 1
#line 50
  onion_response_write(res, "\n<span style=\"color: green;\">OK</span>\n", 39);
#line 1
}
#line 1
static void otemplate_f_0008(dict_res *dr, const char *key, const void *value, int flags){
#line 1
#line 59
  onion_dict_add(dr->dict, "i", value, OD_DUP_VALUE|OD_REPLACE|(flags&OD_TYPE_MASK));
#line 61
  otemplate_f_0009(dr->dict, dr->res);
#line 1
}
#line 1
static void otemplate_f_0009(onion_dict *context, onion_response *res){
#line 1
#line 60
  onion_response_write(res, "\n<li>", 5);
#line 60
  {
#line 60
    const char *tmp;
#line 60
    tmp=onion_dict_get(context, "i");
#line 60
    if (tmp)
#line 60
      onion_response_write0(res, tmp);
#line 60
  }
#line 61
  onion_response_write(res, "</li>\n", 6);
#line 1
}
